# Linear Algebra

In [1]:
import torch

**Using `.sum(axis=n, keepdims=True)` to sum up elements of specified dimension with the number of axes unchanged.**

In [4]:
A = torch.arange(24, dtype=torch.float32).reshape(2,3,4)
A

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]]])

In [8]:
A.sum(axis=0), A.sum(axis=1), A.sum(axis=2)

(tensor([[12., 14., 16., 18.],
         [20., 22., 24., 26.],
         [28., 30., 32., 34.]]),
 tensor([[12., 15., 18., 21.],
         [48., 51., 54., 57.]]),
 tensor([[ 6., 22., 38.],
         [54., 70., 86.]]))

In [13]:
A.sum(axis=0, keepdims=True), A.sum(axis=1, keepdims=True), A.sum(axis=2, keepdims=True)

(tensor([[[12., 14., 16., 18.],
          [20., 22., 24., 26.],
          [28., 30., 32., 34.]]]),
 tensor([[[12., 15., 18., 21.]],
 
         [[48., 51., 54., 57.]]]),
 tensor([[[ 6.],
          [22.],
          [38.]],
 
         [[54.],
          [70.],
          [86.]]]))