# **Preliminaries**

## **-About `ndarray`**

### Getting started

In [1]:
import torch

**USING `torch.arange` to create a row tensor: *[0,1,2,···,10]***

In [2]:
x = torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**USING `.shape` to access a tensor's shape**

In [3]:
x.shape

torch.Size([10])

**USING `.numel` to get the number of elements in tensor**

In [4]:
x.numel()

10

**USING `.reshape()` to change tensors shape specifically**

In [5]:
x.reshape(2, -1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

**USING `torch.zeros` / `torch.ones` to generate tensors with all 0s / 1s**

In [6]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [7]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

**USING `torch.randn()` to generate tensors with elements drawn from a standard Gaussian (normal) distribution with mean 0 and standard deviation 1**

In [8]:
torch.randn(3)

tensor([-0.8861, -1.2334, -1.6932])

**USING `torch.tensor` to generate tensors precisely as specified**

In [17]:
torch.tensor([[1,2,3],[2,4,5]])

tensor([[1, 2, 3],
        [2, 4, 5]])

### Indexing and Slicing

In [19]:
x = torch.tensor([[1,2,3],[2,3,4],[3,4,5],[4,5,6]])

**USING `x[a:b]` to acess the specified elements in tensor x, by which can get the *a_th* element to *(b-1)_th* element**

In [20]:
x[0:2]

tensor([[1, 2, 3],
        [2, 3, 4]])

**NOTICE - Different output between `x[-2]` and `x[-2:-1]`**

In [28]:
x[-2]

tensor([3, 4, 5])

In [29]:
x[-2:-1]

tensor([[3, 4, 5]])

**We could change the elements precisely as well :**

In [31]:
x[2,0] = 6
x

tensor([[1, 2, 3],
        [2, 3, 4],
        [6, 4, 5],
        [4, 5, 6]])