# **Preliminaries**

## **-About `ndarray`**

In [1]:
import torch

**USING `torch.arange` to create a row tensor: *[0,1,2,···,10]***

In [ ]:
x = torch.arange(10)
x

**USING `.shape` to visit a tensor's shape**

In [3]:
x.shape

torch.Size([10])

**USING `.numel` to get the number of elements in tensor**

In [4]:
x.numel()

10

**USING `.reshape()` to change tensors shape specifically**

In [5]:
x.reshape(2, -1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

**USING `torch.zeros` / `torch.ones` to create tensors with all 0s / 1s**

In [7]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [8]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])