# **Preliminaries**

## **-About `ndarray`**

### Getting started

In [1]:
import torch

**USING `torch.arange` to create a row tensor: *[0,1,2,···,10]***

In [2]:
x = torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**USING `.shape` to access a tensor's shape**

In [3]:
x.shape

torch.Size([10])

**USING `.numel` to get the number of elements in tensor**

In [4]:
x.numel()

10

**USING `.reshape()` to change tensors shape specifically**

In [5]:
x.reshape(2, -1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

**USING `torch.zeros` / `torch.ones` to generate tensors with all 0s / 1s**

In [ ]:
a = torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

**USING `torch.zeros_like(a)`/`torch.ones_like(a)` to generate a tensor having the same shape as a.**

In [33]:
torch.ones_like(a)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

**USING `torch.randn()` to generate tensors with elements drawn from a standard Gaussian (normal) distribution with mean 0 and standard deviation 1**

In [8]:
torch.randn(3)

tensor([-0.8111,  0.3013, -0.6521])

**USING `torch.tensor` to generate tensors precisely as specified**

In [9]:
torch.tensor([[1,2,3],[2,4,5]])

tensor([[1, 2, 3],
        [2, 4, 5]])

### Indexing and Slicing

In [10]:
x = torch.tensor([[1,2,3],[2,3,4],[3,4,5],[4,5,6]])

**USING `x[a:b]` to acess the specified elements in tensor x, by which can get the *a_th* element to *(b-1)_th* element**

In [11]:
x[0:2]

tensor([[1, 2, 3],
        [2, 3, 4]])

**NOTICE - Different output between `x[-2]` and `x[-2:-1]`**

In [12]:
x[-2]

tensor([3, 4, 5])

In [13]:
x[-2:-1]

tensor([[3, 4, 5]])

**We could change the elements precisely as well :**

In [14]:
x[2,0] = 6
x

tensor([[1, 2, 3],
        [2, 3, 4],
        [6, 4, 5],
        [4, 5, 6]])

In [15]:
x[:2, :] = 12
x

tensor([[12, 12, 12],
        [12, 12, 12],
        [ 6,  4,  5],
        [ 4,  5,  6]])

### Operations

**`torch.exp()` / `+` / `-` / `*` / `/` / `**`**

In [16]:
x = torch.tensor([1,2,4,8])
y = torch.tensor([2,2,2,2])
torch.exp(y), x + y, x - y, x * y, x / y, x ** y

(tensor([7.3891, 7.3891, 7.3891, 7.3891]),
 tensor([ 3,  4,  6, 10]),
 tensor([-1,  0,  2,  6]),
 tensor([ 2,  4,  8, 16]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1,  4, 16, 64]))

**USING `torch.cat((x,y), dim=)` to concatenate two tensors.(*shape must be same except for the concatenating dimension*)**

In [17]:
X = torch.arange(12, dtype=torch.float32).reshape(3,4)
Y = torch.tensor([[2.0, 1, 3, 4, 5], [1, 2, 3, 4, 5], [4, 3, 2, 1, 5]])
torch.cat((X, Y),dim=1)

tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  3.,  4.,  5.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.,  5.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.,  5.]])

In [18]:
X = torch.arange(12, dtype=torch.float32).reshape(3,4)
Y = torch.tensor([[2.0, 1, 3, 4], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y),dim=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  3.,  4.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])

**USING `==` to judge if two tensors are equal.**

In [19]:
X == Y

tensor([[False,  True, False, False],
        [False, False, False, False],
        [False, False, False, False]])

**USING `.sum()` to summing ALL the elements in the tensor and generate a tensor with only ONE element.**

In [20]:
X.sum()

tensor(66.)

### Broadcasting

**With `Broadcasting mechanism` to perform elementwise binary operations on tensors shapes differ.**

In [31]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a, b, a + b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]),
 tensor([[0, 1],
         [1, 2],
         [2, 3]]))

### Memory

**USING `id()` to access tensor's location in memory,and USING `Z[:] = X + Y` to performing in-place operations.**

In [34]:
Z = torch.tensor([1, 2, 3])
print('id(Z):',id(Z))
Z[:] = Z + 1
print('id(Z):',id(Z))

id(Z): 128219258123184
id(Z): 128219258123184


### Conversion to Other Python Objects

**USING `torch.from_numpy(a)` to change the type of `a` from ndarray to tensor.**

In [35]:
A = X.numpy()
B = torch.from_numpy(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)