# **Preliminaries**

## About `ndarray`

### Getting started

In [1]:
import torch

**Using `torch.arange` to create a row tensor: *[0,1,2,···,10]*.**

In [2]:
x = torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**Using `.shape` to access a tensor's shape.**

In [3]:
x.shape

torch.Size([10])

**Using `.numel` to get the number of elements in tensor.**

In [4]:
x.numel()

10

**Using `.reshape()` to change tensors shape specifically.**

In [5]:
x.reshape(2, -1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

**Using `torch.zeros` / `torch.ones` to generate tensors with all 0s / 1s.**

In [ ]:
a = torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

**Using `torch.zeros_like(a)`/`torch.ones_like(a)` to generate a tensor having the same shape as a.**

In [33]:
torch.ones_like(a)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

**Using `torch.randn()` to generate tensors with elements drawn from a standard Gaussian (normal) distribution with mean 0 and standard deviation 1.**

In [8]:
torch.randn(3)

tensor([-0.8111,  0.3013, -0.6521])

**Using `torch.tensor` to generate tensors precisely as specified.**

In [9]:
torch.tensor([[1,2,3],[2,4,5]])

tensor([[1, 2, 3],
        [2, 4, 5]])

### Indexing and Slicing

In [10]:
x = torch.tensor([[1,2,3],[2,3,4],[3,4,5],[4,5,6]])

**Using `x[a:b]` to acess the specified elements in tensor x, by which can get the *a_th* element to *(b-1)_th* element.**

In [11]:
x[0:2]

tensor([[1, 2, 3],
        [2, 3, 4]])

**NOTICE - Different output between `x[-2]` and `x[-2:-1]`.**

In [12]:
x[-2]

tensor([3, 4, 5])

In [13]:
x[-2:-1]

tensor([[3, 4, 5]])

**We could change the elements precisely as well :**

In [14]:
x[2,0] = 6
x

tensor([[1, 2, 3],
        [2, 3, 4],
        [6, 4, 5],
        [4, 5, 6]])

In [15]:
x[:2, :] = 12
x

tensor([[12, 12, 12],
        [12, 12, 12],
        [ 6,  4,  5],
        [ 4,  5,  6]])

### Operations

**`torch.exp()` / `+` / `-` / `*` / `/` / `**`**

In [16]:
x = torch.tensor([1,2,4,8])
y = torch.tensor([2,2,2,2])
torch.exp(y), x + y, x - y, x * y, x / y, x ** y

(tensor([7.3891, 7.3891, 7.3891, 7.3891]),
 tensor([ 3,  4,  6, 10]),
 tensor([-1,  0,  2,  6]),
 tensor([ 2,  4,  8, 16]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1,  4, 16, 64]))

**Using `torch.cat((x,y), dim=)` to concatenate two tensors.(*shape must be same except for the concatenating dimension*)**

In [17]:
X = torch.arange(12, dtype=torch.float32).reshape(3,4)
Y = torch.tensor([[2.0, 1, 3, 4, 5], [1, 2, 3, 4, 5], [4, 3, 2, 1, 5]])
torch.cat((X, Y),dim=1)

tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  3.,  4.,  5.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.,  5.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.,  5.]])

In [18]:
X = torch.arange(12, dtype=torch.float32).reshape(3,4)
Y = torch.tensor([[2.0, 1, 3, 4], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y),dim=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  3.,  4.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])

**Using `==` to judge if two tensors are equal.**

In [19]:
X == Y

tensor([[False,  True, False, False],
        [False, False, False, False],
        [False, False, False, False]])

**Using `.sum()` to summing ALL the elements in the tensor and generate a tensor with only ONE element.**

In [20]:
X.sum()

tensor(66.)

### Broadcasting

**With `Broadcasting mechanism` to perform elementwise binary operations on tensors shapes differ.**

In [31]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a, b, a + b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]),
 tensor([[0, 1],
         [1, 2],
         [2, 3]]))

### Memory

**Using `id()` to access tensor's location in memory,and Using `Z[:] = X + Y` to performing in-place operations.**

In [34]:
Z = torch.tensor([1, 2, 3])
print('id(Z):',id(Z))
Z[:] = Z + 1
print('id(Z):',id(Z))

id(Z): 128219258123184
id(Z): 128219258123184


### Conversion to Other Python Objects

**USING `torch.from_numpy(a)` to change the type of `a` from ndarray to tensor.**

In [35]:
A = X.numpy()
B = torch.from_numpy(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

## About `pandas`

In [2]:
import pandas as pd

In [4]:
fruits = pd.DataFrame({'Apples':[21,12],'Bananas':[98,32]},index=['2017 Sales','2018 Sales'])
fruits

,Apples,Bananas
2017 Sales,21,98
2018 Sales,12,32


### Reading the Dataset

**Using `pd.read_csv(file_path)` to load the dataset.**

In [5]:
data = pd.read_csv('/home/yanzi888/d2l/d2l-EN/data/house_tiny.csv')
print(data)

   NumRooms RoofType   Price
0       NaN      NaN  127500
1       2.0      NaN  106000
2       4.0    Slate  178100
3       NaN      NaN  140000


### Data Preparation

**In Supervised Learning, our first step is to separate columns into inputs and outputs with *Slicing(切片)*, Using `data.iloc[]` to access these multiple categories of data.**

**For missing categorical values, using `pd.get_dummies(inputs, dummy_na=True)` treat `NaN` as a category through setting extra columns.**

In [ ]:
inputs, targets = data.iloc[:, 0:2], data.iloc[:, 2]
inputs = pd.get_dummies(inputs, dummy_na=True)
inputs_false = pd.get_dummies(inputs, dummy_na=False)
print(inputs),print(inputs_false)

   NumRooms  RoofType_Slate  RoofType_nan
0       NaN           False          True
1       2.0           False          True
2       4.0            True         False
3       NaN           False          True
   NumRooms  RoofType_Slate  RoofType_nan
0       NaN           False          True
1       2.0           False          True
2       4.0            True         False
3       NaN           False          True


(None, None)

**For missing numerical values, using `.fillna(.mean())` to replace `NaN` entries with the mean value of the corresponding column.**

In [ ]:
inputs = inputs.fillna(inputs.mean())
print(inputs)

   NumRooms  RoofType_Slate  RoofType_nan
0       3.0           False          True
1       2.0           False          True
2       4.0            True         False
3       3.0           False          True


### Convertion to the Tensor Format

**Using `torch.tensor(.to_numpy(dtype=float))` to load the *numericalized(数字化的)* data into tensors**

In [ ]:
import torch

In [ ]:
x = torch.tensor(inputs.to_numpy(dtype=float))
y = torch.tensor(targets.to_numpy(dtype=float))
x, y

## The following cell inspects how to deal with `Iris Dataset`.

In [ ]:
from ucimlrepo import fetch_ucirepo 
import torch
import pandas as pd

In [ ]:
iris = fetch_ucirepo(id=53) 

In [ ]:
inputs = iris.data.features 
targets = iris.data.targets

In [ ]:
print(iris)

{'data': {'ids': None, 'features':      sepal length  sepal width  petal length  petal width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns], 'targets':               class
0       Iris-setosa
1       Iris-setosa
2       Iris-setosa
3       Iris-setosa
4       Iris-setosa
..              ...
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica
149  Iris-vir

In [ ]:
# metadata 
print(iris.metadata) 
  
# variable information 
print(iris.variables) 

{'uci_id': 53, 'name': 'Iris', 'repository_url': 'https://archive.ics.uci.edu/dataset/53/iris', 'data_url': 'https://archive.ics.uci.edu/static/public/53/data.csv', 'abstract': 'A small classic dataset from Fisher, 1936. One of the earliest known datasets used for evaluating classification methods.\n', 'area': 'Biology', 'tasks': ['Classification'], 'characteristics': ['Tabular'], 'num_instances': 150, 'num_features': 4, 'feature_types': ['Real'], 'demographics': [], 'target_col': ['class'], 'index_col': None, 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 1936, 'last_updated': 'Tue Sep 12 2023', 'dataset_doi': '10.24432/C56C76', 'creators': ['R. A. Fisher'], 'intro_paper': {'ID': 191, 'type': 'NATIVE', 'title': 'The Iris data set: In search of the source of virginica', 'authors': 'A. Unwin, K. Kleinman', 'venue': 'Significance, 2021', 'year': 2021, 'journal': 'Significance, 2021', 'DOI': '1740-9713.01589', 'URL': 'https://www.semanticscholar.org

In [ ]:
inputs = inputs.fillna(inputs.mean())
print(inputs)

     sepal length  sepal width  petal length  petal width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]


In [ ]:
targets = pd.get_dummies(targets, dummy_na=True)
print(targets)

     class_Iris-setosa  class_Iris-versicolor  class_Iris-virginica  class_nan
0                 True                  False                 False      False
1                 True                  False                 False      False
2                 True                  False                 False      False
3                 True                  False                 False      False
4                 True                  False                 False      False
..                 ...                    ...                   ...        ...
145              False                  False                  True      False
146              False                  False                  True      False
147              False                  False                  True      False
148              False                  False                  True      False
149              False                  False                  True      False

[150 rows x 4 columns]


In [ ]:
X = torch.tensor(inputs.to_numpy(dtype=float))
y = torch.tensor(targets.to_numpy(dtype=float))
X, y

(tensor([[5.1000, 3.5000, 1.4000, 0.2000],
         [4.9000, 3.0000, 1.4000, 0.2000],
         [4.7000, 3.2000, 1.3000, 0.2000],
         [4.6000, 3.1000, 1.5000, 0.2000],
         [5.0000, 3.6000, 1.4000, 0.2000],
         [5.4000, 3.9000, 1.7000, 0.4000],
         [4.6000, 3.4000, 1.4000, 0.3000],
         [5.0000, 3.4000, 1.5000, 0.2000],
         [4.4000, 2.9000, 1.4000, 0.2000],
         [4.9000, 3.1000, 1.5000, 0.1000],
         [5.4000, 3.7000, 1.5000, 0.2000],
         [4.8000, 3.4000, 1.6000, 0.2000],
         [4.8000, 3.0000, 1.4000, 0.1000],
         [4.3000, 3.0000, 1.1000, 0.1000],
         [5.8000, 4.0000, 1.2000, 0.2000],
         [5.7000, 4.4000, 1.5000, 0.4000],
         [5.4000, 3.9000, 1.3000, 0.4000],
         [5.1000, 3.5000, 1.4000, 0.3000],
         [5.7000, 3.8000, 1.7000, 0.3000],
         [5.1000, 3.8000, 1.5000, 0.3000],
         [5.4000, 3.4000, 1.7000, 0.2000],
         [5.1000, 3.7000, 1.5000, 0.4000],
         [4.6000, 3.6000, 1.0000, 0.2000],
         [5

## About `Linear Algebra`

In [ ]:
import torch

**Using `.sum(axis=n, keepdims=True)` to sum up elements of specified dimension with the number of axes unchanged.**

In [ ]:
A = torch.arange(24, dtype=torch.float32).reshape(2,3,4)
A

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]]])

In [ ]:
A.sum(axis=0), A.sum(axis=1), A.sum(axis=2)

(tensor([[12., 14., 16., 18.],
         [20., 22., 24., 26.],
         [28., 30., 32., 34.]]),
 tensor([[12., 15., 18., 21.],
         [48., 51., 54., 57.]]),
 tensor([[ 6., 22., 38.],
         [54., 70., 86.]]))

In [ ]:
A.sum(axis=0, keepdims=True), A.sum(axis=1, keepdims=True), A.sum(axis=2, keepdims=True)

(tensor([[[12., 14., 16., 18.],
          [20., 22., 24., 26.],
          [28., 30., 32., 34.]]]),
 tensor([[[12., 15., 18., 21.]],
 
         [[48., 51., 54., 57.]]]),
 tensor([[[ 6.],
          [22.],
          [38.]],
 
         [[54.],
          [70.],
          [86.]]]))

## About `Automatic Differentiation`

### Backward for Scalar

In [1]:
import torch

In [2]:
x = torch.arange(4.0, requires_grad=True)

**Using `.grad` to access a tensor's gradient.**

In [3]:
x.grad

In [4]:
y = 2 * torch.dot(x, x)

**Using `.backward()` to take the gradient: $\nabla_{\mathbf{X}} f(\mathbf{x})$**

In [5]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

**Using `.grad.zero_()` to initialize the gradient.**

In [6]:
x.grad.zero_()

tensor([0., 0., 0., 0.])

### Backward for Non-Scalar Variables

**Since the following `y` is a vector, we should set a specified vector called `gradient` to let `backward()` compute $\mathbf{v}^\top \partial_{\mathbf{x}} \mathbf{y}$ rather than $\partial_{\mathbf{x}} \mathbf{y}$, which is equivalent to multiplying `y` by $\mathbf{v}^\top$, then produce the `backward()`.**

In [7]:
y = x * x
y.backward(gradient=torch.ones(len(y)))
x.grad

tensor([0., 2., 4., 6.])

### Detaching Computation

**Using `.detach()` to wipe out the provenance(how it was created) to see it as a constant.**

In [16]:
x.grad.zero_()
y = x * x
u = y.detach()
z = u * x

z.backward(gradient=torch.ones(len(z)))
x.grad == u

tensor([True, True, True, True])

**Which should be noticed that the computational graph leading to `y` presists and thus we can calculate the gradient of `y` with respect to `x`.**

In [17]:
x.grad.zero_()
y.backward(gradient=torch.ones(len(y)))
x.grad == 2 * x

tensor([True, True, True, True])

## About Probability and Statistics

In [7]:
%matplotlib inline
import random
import torch
from torch.distributions.multinomial import Multinomial
from d2l import torch as d2l

**When assigned a probability vector *(fair_probs)*, using `Multinomial(n, fair_probs).sample()` / tosses to access the *frequency*.**

In [8]:
fair_probs = torch.ones(6) / 6
Multinomial(100, fair_probs).sample() / 100

tensor([0.1600, 0.1100, 0.1600, 0.2100, 0.1800, 0.1800])